library(igraph)
args<-commandArgs(T)
a <- read.table(args[1],sep="\t",header=T)
p<-make_graph(t(a[,1:2]),directed=F)
eccentricity <- eccentricity(p,mode="all",vids=V(p))
closeness <- closeness(p,normalized=T)
degree <- degree(p)
eigen_centrality <- eigen_centrality(p)$vector
total <- cbind (eccentricity,closeness,degree,eigen_centrality)
total <- cbind(Gene=row.names(total),total)
write.table(total,args[2],quote=F,sep="\t",row.names=F)
a<-distances(p)
a <- cbind(Gene=row.names(a),a)
write.table(a,args[3],quote=F,sep="\t",row.names=F)
a<-transitivity(p)
b<-average.path.length(p)
a <- cbind (a,b)
write.table(a,args[4],row.names=F)